### ISSUE TITLE
Missing grobot_utilities.msg

### ISSUE THREAD

**Issue by harsh2297** [nlamprian/grobot#1]
In grobot/grobot_utilities/scripts/patrol_server.py
You are importing PatrolAction, PatrolFeedback from “grobot_utilities.msg” but its not there in the repository. 
also can you mention all ros distro, ros packages required to run this?

**Comment by nlamprian** [comment]
Any ros distro you have will probably do. You can get the dependencies of grobot with
```
rosdep keys --from-paths src/grobot/
```
Any of the dependencies not available in Ubuntu, you'll have to download in the workspace by yourself.

The modules you refer to are generated when compiling the package.
